### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by KoxSosen** [JLyne/ProxyQueues#1]
Hello! 

I'm trying to build the maven project using ```mvn clean package```. However, I'm getting errors regarding Prometheus, due to possbily moved repo. Errors:

![image](https://user-images.githubusercontent.com/67807644/107856514-eedadc80-6e28-11eb-980b-31ceb3eeed2b.png)

[ERROR] Failed to execute goal on project proxyqueues: Could not resolve dependencies for project uk.co.notnull:proxyqueues:jar:1.0: Failed to collect dependencies at de.sldk.mc:velocity-prometheus-exporter:jar:2.0.2: Failed to read artifact descriptor for de.sldk.mc:velocity-prometheus-exporter:jar:2.0.2: Could not transfer artifact de.sldk.mc:velocity-prometheus-exporter:pom:2.0.2 from/to nukkitxsnapshots (https://repo.nukkitx.com/maven-snapshots): Transfer failed for https://repo.nukkitx.com/maven-snapshots/de/sldk/mc/velocity-prometheus-exporter/2.0.2/velocity-prometheus-exporter-2.0.2.pom 409 Conflict -> [Help 1]

**Comment by KoxSosen** [comment]
Issue still exists after updating my local repo.

**Comment by KoxSosen** [comment]
Fixed.

**Comment by MWHunter** [comment]
I still have this issue and cannot build because of the same error

**Comment by MWHunter** [comment]
https://xkcd.com/979/

**Comment by JLyne** [comment]
For what it's worth, the project should now be buildable as is
